  

class MetaFinancialLeverageRadio:
    """## Return:  meta data"""


    fixed_asset = """[Τεκμηρίωση assets]
[Εξετάζοντας τα περιουσιακά στοιχεία του Ενεργητικού διαπιστώνουμε ότι:]
[Μερικά από αυτά, όπως είναι οικόπεδα, κτίρια, μηχανήματα, μεταφορικά μέσα, έπιπλα και λοιπός εξοπλισμός, διπλώματα ευρεσιτεχνίας κτλ.]
[αποτελούν μόνιμο εξοπλισμό της επιχείρησης και προορίζονται να την εξυπηρετούν για χρονικό διάστημα μεγαλύτερο του έτους. Αυτά λέγονται Πάγια.]
[Documentation assets]
[Examining the assets of the Asset we find that:]
[Some of them, such as land, buildings, machinery, means of transport, furniture and other equipment, patents, etc.]
[are permanent equipment of the company and are intended to serve it for a period longer than a year. This is what you call a fixed asset]
"""

    interest = """[Τεκμηρίωση interest]
[Τόκος είναι η αποζημίωση σε χρήματα που είναι υποχρεωμένος να δώσει ο οφειλέτης στο δανειστή για ορισμένη ποσότητα χρηματικού δανείου που πήρε για συγκεκριμένη χρονική περίοδο.]
[Οι οικονομολόγοι συχνά αναφέρονται στον τόκο ως αμοιβή για τη χρησιμοποίηση χρηματικού κεφαλαίου, ή ως τιμή με την οποία χρεώνεται η χρήση κεφαλαίου. Ο λόγος του τόκου προς το κεφάλαιο λέγεται επιτόκιο. ]
[Documentation interest]
[Interest is the compensation in money that the debtor is obliged to give to the lender for a certain amount of money borrowed for a certain period of time.]
[Economists often refer to interest as a fee for the use of money capital, or as the price at which the use of capital is needed. The ratio of the interest to the principal is called the interest rate.]
"""
    tax_rate = """[Τεκμηρίωση tax_rate]
[Ο φορολογικός συντελεστής (tax_rate) είναι ένα ποσοστό που αντιπροσωπεύει το ποσό του φόρου που επιβάλλεται στα κέρδη μιας επιχείρησης ή ενός ατόμου. Εκφράζεται συνήθως ως δεκαδικός αριθμός ή ποσοστό.]
[Documentation tax_rate]
[The tax rate (tax_rate) is a percentage that represents the amount of tax levied on the profits of a business or an individual. It is usually expressed as a decimal number or percentage.]
"""

class MetaGrossMargin:
    """## Return:  meta data
    arithmetical gross profit => Αριθμοδείκτης μικτού κέρδους
    """

    gross_operating_profit = """[Τεκμηρίωση gross_operating_profit]
[Το ακαθάριστο λειτουργικό κέρδος (ή Gross Operating Profit) αναφέρεται στο κέρδος που προκύπτει από τις λειτουργικές δραστηριότητες μιας επιχείρησης, πριν αφαιρεθούν τα λειτουργικά έξοδα, οι τόκοι, οι φόροι και άλλες εξωτερικές δαπάνες.]
[Στην ουσία, είναι το κέρδος που παράγεται από την κύρια δραστηριότητα της επιχείρησης, χωρίς να λαμβάνονται υπόψη οι μη λειτουργικές δραστηριότητες ή οι μη-λειτουργικές δαπάνες (όπως τα χρηματοοικονομικά έξοδα ή τα έκτακτα έξοδα).]
[Documentation gross_operating_profit]
[Gross Operating Profit (or Gross Operating Profit) refers to the profit obtained from the operating activities of a business, before deducting operating expenses, interest, taxes and other external costs.]
[In essence, it is the profit generated by the main activity of the business, without taking into account non-operating activities or non-operating expenses (such as financial expenses or extraordinary expenses).]
"""
   
    net_operating_profit = """[Τεκμηρίωση net_operating_profit]
[Το καθαρό λειτουργικό κέρδος (ή Net Operating Profit – NOP) αναφέρεται στο ποσό του κέρδους που απομένει από τις λειτουργικές δραστηριότητες μιας επιχείρησης αφού αφαιρεθούν όλα τα άμεσα και έμμεσα λειτουργικά έξοδα, εκτός από τους τόκους και τους φόρους.]
[Δηλαδή, είναι το κέρδος που έχει απομείνει αφού καλυφθούν οι δαπάνες που συνδέονται με την παραγωγή, τη διάθεση και τη διαχείριση των προϊόντων ή υπηρεσιών της επιχείρησης.]
[Documentation net_operating_profit]
[Net Operating Profit (or NOP) refers to the amount of profit remaining from the operating activities of a business after deducting all direct and indirect operating expenses, excluding interest and taxes.]
[That is, it is the profit that is left after covering the costs associated with the production, distribution and management of the company's products or services.]

"""
    sales = """[Τεκμηρίωση sales]
[Ο όρος "πώλησης" αναφέρεται στην πράξη της ανταλλαγής αγαθών ή υπηρεσιών για χρήματα ή άλλους πόρους. Στο οικονομικό και επιχειρηματικό πλαίσιο, η πώληση είναι μια βασική συναλλαγή που επιτρέπει στις επιχειρήσεις να παράγουν έσοδα και να λειτουργούν.]
[Η πώληση δεν περιορίζεται μόνο στην ανταλλαγή προϊόντων, αλλά μπορεί να περιλαμβάνει και την παροχή υπηρεσιών.]
[Documentation sales]
[The term "sale" refers to the act of exchanging goods or services for money or other resources. In the economic and business context, selling is a key transaction that allows businesses to generate revenue and operate.]
[Selling is not only limited to the exchange of products, but may also include the provision of services.]
"""
    net_profit_of_use = """[Τεκμηρίωση net_profit_of_use]
[Το καθαρό κέρδος χρήσης αναφέρεται στο καθαρό κέρδος που απομένει στην επιχείρηση μετά την αφαίρεση όλων των εξόδων λειτουργίας, φόρων, τόκων και άλλων υποχρεώσεων από τα έσοδα της επιχείρησης κατά τη διάρκεια μιας συγκεκριμένης χρήσης (χρηματοοικονομικής περιόδου).
[Αυτή η έννοια μπορεί να έχει διάφορους συνυπολογισμούς, ανάλογα με το τι περιλαμβάνει το "καθαρό" κέρδος, και συχνά συνδέεται με τον λογιστικό ορισμό του καθαρού κέρδους.]
[Documentation net_profit_of_use]
[Net profit for a year refers to the net profit left in the business after deducting all operating expenses, taxes, interest and other liabilities from the revenue of the business during a particular year (financial period).]
[Αυτή η έννοια μπορεί να έχει διάφορους συνυπολογισμούς, ανάλογα με το τι περιλαμβάνει το "καθαρό" κέρδος, και συχνά συνδέεται με τον λογιστικό ορισμό του καθαρού κέρδους.]
"""
    total_of_these_funds = """[Τεκμηρίωση total_of_these_funds]
[Το σύνολο θέσης κεφαλαίων αναφέρεται στο συνολικό ποσό κεφαλαίων που χρησιμοποιεί μια επιχείρηση ή ένας επενδυτής για να χρηματοδοτήσει τις δραστηριότητες ή τις επενδύσεις του.]
[Αυτό το ποσό μπορεί να περιλαμβάνει διάφορες πηγές χρηματοδότησης, όπως ιδία κεφάλαια, δανεισμό ή άλλες μορφές χρηματοδότησης.]
[Documentation total_of_these_funds]
[Total capital position refers to the total amount of capital that a business or investor has to finance its operations or investments.]
[This amount may include various sources of financing, such as equity, debt or other forms of financing.]
"""

class MetaMaintenanceRepair:
    """## Return:  meta data
    arithmetical gross profit => Αριθμοδείκτης μικτού κέρδους"""


    net_sales = """[Τεκμηρίωση net_sales]
[Η αξία των πωλήσεων μιας οικονομικής μονάδας μετά την αφαίρεση των φόρων (πχ. ΦΠΑ), των επιστροφών, των εκπτώσεων και της αξίας των κατεστραμμένων προϊόντων]
[Documentation net_sales]
[The value of sales of an economic unit after deduction of taxes (e.g. VAT), returns, discounts and the value of damaged products]
"""
    maintenance_and_repair_costs = """[Τεκμηρίωση maintenance_and_repair_costs]
Τα έξοδα συντήρησης και επισκευής (maintenance and repair costs) αναφέρονται σε εκείνα τα έξοδα που προκύπτουν για τη διατήρηση των πάγιων περιουσιακών στοιχείων ή των εγκαταστάσεων σε λειτουργική κατάσταση και την αποκατάσταση των τυχόν ζημιών ή φθορών που προκύπτουν από τη χρήση τους.]
[Αυτά τα έξοδα είναι συνήθως απαραίτητα για την καλή λειτουργία και μακροχρόνια διάρκεια ζωής των υποδομών, του εξοπλισμού και των μηχανημάτων.]
[Documentation maintenance_and_repair_costs]
[Maintenance and repair costs (maintenance and repair costs) refer to those costs incurred to maintain the fixed assets or facilities in an operational condition and to repair any damages or damages resulting from their use.]
[These costs are usually necessary for the good operation and long life of the infrastructure, equipment and machinery.]
"""
    fixed_assets_before_depreciation = """[Τεκμηρίωση fixed_assets_before_depreciation]
[Τα πάγια στοιχεία πριν από τις αποσβέσεις (fixed assets before depreciation) αναφέρονται στην αξία των πάγιων περιουσιακών στοιχείων μιας επιχείρησης πριν εφαρμοστούν οι αποσβέσεις. ]
[Τα πάγια στοιχεία περιλαμβάνουν τα υλικά ή άυλα περιουσιακά στοιχεία που χρησιμοποιούνται από την επιχείρηση για μεγαλύτερο χρονικό διάστημα, συνήθως πάνω από 1 έτος, και δεν προορίζονται για άμεση πώληση.]
[Documentation fixed_assets_before_depreciation]
[Fixed assets before depreciation refer to the value of a company's fixed assets before depreciation is applied.]
[Fixed assets include tangible or intangible assets that are used by the business for a longer period of time, usually more than 1 year, and are not intended for immediate sale.]
"""
    depreciation_of_use = """[Τεκμηρίωση depreciation_of_use]
[Η απόσβεση χρήσης (depreciation of use) αναφέρεται στον τρόπο με τον οποίο ένα πάγιο περιουσιακό στοιχείο χάνει την αξία του με την πάροδο του χρόνου, λόγω της χρήσης του στην παραγωγική διαδικασία ή στις καθημερινές λειτουργίες της επιχείρησης.]
[Η συγκεκριμένη φράση τονίζει τη συσχέτιση της απόσβεσης με την ένταση και διάρκεια χρήσης του περιουσιακού στοιχείου.]
[Documentation depreciation_of_use]
[Depreciation of use refers to the way in which a fixed asset loses its value over time, due to its use in the production process or in the day-to-day operations of the business.]
[This phrase emphasizes the correlation of depreciation with the intensity and duration of use of the asset.]
"""
    fixed_assets_for_depreciation = """[Τεκμηρίωση fixed_assets_for_depreciation]
[Ο όρος πάγια στοιχεία για απόσβεση (fixed assets for depreciation) αναφέρεται στα πάγια περιουσιακά στοιχεία που υπόκεινται σε απόσβεση, δηλαδή εκείνα που χρησιμοποιούνται από την επιχείρηση στις δραστηριότητές της και έχουν περιορισμένη ωφέλιμη διάρκεια ζωής.]
[Documentation fixed_assets_for_depreciation]
[The term fixed assets for depreciation (fixed assets for depreciation) refers to the assets that are subject to depreciation, that is, those that are referred by the company to its activities and have a limited useful life.]
"""
    due_to_operating_expenses = """"[Τεκμηρίωση due_to_operating_expenses]
[Ο όρος "due to operating expenses" μπορεί να αποδοθεί στα ελληνικά ως "λόγω λειτουργικών εξόδων" ή "εξαιτίας λειτουργικών εξόδων".]
[Χρησιμοποιείται για να περιγράψει δαπάνες ή υποχρεώσεις που προκύπτουν από την καθημερινή λειτουργία μιας επιχείρησης.]
[Μπορεί να αναφέρεται σε λόγους για τους οποίους μειώνονται τα έσοδα ή το κέρδος, π.χ. "Η μείωση των καθαρών κερδών οφείλεται στα υψηλά λειτουργικά έξοδα.]
[Documentation due_to_operating_expenses]
[It is used to describe expenses or liabilities arising from the day-to-day running of a business.]
[It can refer to reasons why revenue or profit is falling, e.g. "The decrease in net profits is due to high operating expenses.]
"""

class MetaReturnTotalCapitalEmployed:
    """## Return:  meta data"""
    
    net_profit = """[Τεκμηρίωση net_profit]
[Στις επιχειρήσεις, το καθαρό εισόδημα ή τα καθαρά κέρδη είναι τα έσοδα μείον το κόστος πωληθέντων αγαθών, τα έξοδα και τους φόρους για μια λογιστική χρήση.]
[Documentation net_profit]
[In business, net income or net profit is revenue minus cost of goods sold, expenses, and taxes for an accounting year.]
"""
    net_sales = """[Τεκμηρίωση net_sales]
[Η αξία των πωλήσεων μιας οικονομικής μονάδας μετά την αφαίρεση των φόρων (πχ. ΦΠΑ), των επιστροφών, των εκπτώσεων και της αξίας των κατεστραμμένων προϊόντων]
[Documentation net_sales]
[The value of sales of an economic unit after deduction of taxes (e.g. VAT), returns, discounts and the value of damaged products]
"""
    interest = """[Τεκμηρίωση interest]
[Τόκος είναι η αποζημίωση σε χρήματα που είναι υποχρεωμένος να δώσει ο οφειλέτης στο δανειστή για ορισμένη ποσότητα χρηματικού δανείου που πήρε για συγκεκριμένη χρονική περίοδο.]
[Οι οικονομολόγοι συχνά αναφέρονται στον τόκο ως αμοιβή για τη χρησιμοποίηση χρηματικού κεφαλαίου, ή ως τιμή με την οποία χρεώνεται η χρήση κεφαλαίου. Ο λόγος του τόκου προς το κεφάλαιο λέγεται επιτόκιο. ]
[Documentation interest]
[Interest is the compensation in money that the debtor is obliged to give to the lender for a certain amount of money borrowed for a certain period of time.]
[Economists often refer to interest as a fee for the use of money capital, or as the price at which the use of capital is needed. The ratio of the interest to the principal is called the interest rate.]
"""
    tax_rate = """[Τεκμηρίωση tax_rate]
[Ο φορολογικός συντελεστής (tax_rate) είναι ένα ποσοστό που αντιπροσωπεύει το ποσό του φόρου που επιβάλλεται στα κέρδη μιας επιχείρησης ή ενός ατόμου. Εκφράζεται συνήθως ως δεκαδικός αριθμός ή ποσοστό.]
[Documentation tax_rate]
[The tax rate (tax_rate) is a percentage that represents the amount of tax levied on the profits of a business or an individual. It is usually expressed as a decimal number or percentage.]
"""
    total_capital = """[Τεκμηρίωση total_capital]
[ο συνολικό κεφάλαιο αναφέρεται στο άθροισμα όλων των οικονομικών πόρων που διαθέτει μία επιχείρηση ή ένα άτομο, συμπεριλαμβανομένων ιδίων κεφαλαίων και δανειακού κεφαλαίου. Περιλαμβάνει όλα τα στοιχεία ενεργητικού που χρησιμοποιούνται για την επίτευξη κέρδους,]
[όπως μετρητά, επενδύσεις, ακίνητα και εξοπλισμό. Είναι ένας σημαντικός δείκτης για την οικονομική κατάσταση και τη χρηματοδοτική ικανότητα.]
[Documentation total_capital]
[Total capital refers to the sum of all financial resources available to a business or an individual, including equity and debt capital. It includes all assets used to make a profit.]
[such as cash, investments, property and equipment. It is an important indicator of financial status and financial capacity.]
"""





# def __str__(self):
#     attributes = [
#         self.circulating_assets,
#         self.short_term_liabilities,
#         self.available_cash,
#         self.forecast_daily_expenses,
#         self.requirements,
#     ]
#     return "\n\n".join(map(str, attributes))