[project]
name = "net_analysis"
version = "0.0.6"
description = "A package that aims to cover the analysis of the financial situations of businesses with the help of numerical indicators."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "ruff>=0.8.6",
    "tox>=4.23.2",
]

[tool.uv.workspace]
members = ["net_business_analysis/net_analysis"]
