[project]
name = "net_analysis"
version = "0.0.6"
description = "A package that aims to cover the analysis of the financial situations of businesses with the help of numerical indicators."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "diagrams>=0.24.1",
    "icecream>=2.1.3",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "pytest-html>=4.1.1",
    "ruff>=0.8.6",
    "setuptools>=75.7.0",
    "tox>=4.23.2",
]

[tool.uv.workspace]
members = ["net_business_analysis/net_analysis"]
