
class MetaData:
    """## Return:  meta data
arithmetical gross profit => Αριθμοδείκτης μικτού κέρδους
"""
    gross_operating_profit = """[Τεκμηρίωση gross_operating_profit]
[Το ακαθάριστο λειτουργικό κέρδος (ή Gross Operating Profit) αναφέρεται στο κέρδος που προκύπτει από τις λειτουργικές δραστηριότητες μιας επιχείρησης, πριν αφαιρεθούν τα λειτουργικά έξοδα, οι τόκοι, οι φόροι και άλλες εξωτερικές δαπάνες.]
[Στην ουσία, είναι το κέρδος που παράγεται από την κύρια δραστηριότητα της επιχείρησης, χωρίς να λαμβάνονται υπόψη οι μη λειτουργικές δραστηριότητες ή οι μη-λειτουργικές δαπάνες (όπως τα χρηματοοικονομικά έξοδα ή τα έκτακτα έξοδα).]
[Documentation gross_operating_profit]
[Gross Operating Profit (or Gross Operating Profit) refers to the profit obtained from the operating activities of a business, before deducting operating expenses, interest, taxes and other external costs.]
[In essence, it is the profit generated by the main activity of the business, without taking into account non-operating activities or non-operating expenses (such as financial expenses or extraordinary expenses).]
"""
    net_sales = """[Τεκμηρίωση net_sales]
[Η αξία των πωλήσεων μιας οικονομικής μονάδας μετά την αφαίρεση των φόρων (πχ. ΦΠΑ), των επιστροφών, των εκπτώσεων και της αξίας των κατεστραμμένων προϊόντων]
[Documentation net_sales]
[The value of sales of an economic unit after deduction of taxes (e.g. VAT), returns, discounts and the value of damaged products]
"""
    net_operating_profit = """[Τεκμηρίωση net_operating_profit]
[Το καθαρό λειτουργικό κέρδος (ή Net Operating Profit – NOP) αναφέρεται στο ποσό του κέρδους που απομένει από τις λειτουργικές δραστηριότητες μιας επιχείρησης αφού αφαιρεθούν όλα τα άμεσα και έμμεσα λειτουργικά έξοδα, εκτός από τους τόκους και τους φόρους.]
[Δηλαδή, είναι το κέρδος που έχει απομείνει αφού καλυφθούν οι δαπάνες που συνδέονται με την παραγωγή, τη διάθεση και τη διαχείριση των προϊόντων ή υπηρεσιών της επιχείρησης.]
[Documentation net_operating_profit]
[Net Operating Profit (or NOP) refers to the amount of profit remaining from the operating activities of a business after deducting all direct and indirect operating expenses, excluding interest and taxes.]
[That is, it is the profit that is left after covering the costs associated with the production, distribution and management of the company's products or services.]

"""
    sales = """[Τεκμηρίωση sales]
[Ο όρος "πώλησης" αναφέρεται στην πράξη της ανταλλαγής αγαθών ή υπηρεσιών για χρήματα ή άλλους πόρους. Στο οικονομικό και επιχειρηματικό πλαίσιο, η πώληση είναι μια βασική συναλλαγή που επιτρέπει στις επιχειρήσεις να παράγουν έσοδα και να λειτουργούν.]
[Η πώληση δεν περιορίζεται μόνο στην ανταλλαγή προϊόντων, αλλά μπορεί να περιλαμβάνει και την παροχή υπηρεσιών.]
[Documentation sales]
[The term "sale" refers to the act of exchanging goods or services for money or other resources. In the economic and business context, selling is a key transaction that allows businesses to generate revenue and operate.]
[Selling is not only limited to the exchange of products, but may also include the provision of services.]
"""
    net_profit_of_use = """[Τεκμηρίωση net_profit_of_use]
[Το καθαρό κέρδος χρήσης αναφέρεται στο καθαρό κέρδος που απομένει στην επιχείρηση μετά την αφαίρεση όλων των εξόδων λειτουργίας, φόρων, τόκων και άλλων υποχρεώσεων από τα έσοδα της επιχείρησης κατά τη διάρκεια μιας συγκεκριμένης χρήσης (χρηματοοικονομικής περιόδου).
[Αυτή η έννοια μπορεί να έχει διάφορους συνυπολογισμούς, ανάλογα με το τι περιλαμβάνει το "καθαρό" κέρδος, και συχνά συνδέεται με τον λογιστικό ορισμό του καθαρού κέρδους.]
[Documentation net_profit_of_use]
[Net profit for a year refers to the net profit left in the business after deducting all operating expenses, taxes, interest and other liabilities from the revenue of the business during a particular year (financial period).]
[Αυτή η έννοια μπορεί να έχει διάφορους συνυπολογισμούς, ανάλογα με το τι περιλαμβάνει το "καθαρό" κέρδος, και συχνά συνδέεται με τον λογιστικό ορισμό του καθαρού κέρδους.]
"""
    total_of_these_funds = """[Τεκμηρίωση total_of_these_funds]
[Το σύνολο θέσης κεφαλαίων αναφέρεται στο συνολικό ποσό κεφαλαίων που χρησιμοποιεί μια επιχείρηση ή ένας επενδυτής για να χρηματοδοτήσει τις δραστηριότητες ή τις επενδύσεις του.]
[Αυτό το ποσό μπορεί να περιλαμβάνει διάφορες πηγές χρηματοδότησης, όπως ιδία κεφάλαια, δανεισμό ή άλλες μορφές χρηματοδότησης.]
[Documentation total_of_these_funds]
[Total capital position refers to the total amount of capital that a business or investor has to finance its operations or investments.]
[This amount may include various sources of financing, such as equity, debt or other forms of financing.]
"""

class GrossMargin:
    """
    ### Τεκμηρίωση\n
    Η κλάση Μικτό περιθώριο,  ενσωματώνει όλους   εκείνους τους λογαριασμούς που χρησιμοποιούν οι μέθοδοι του.\n
    Αυτή οι λογαριασμοί  Αρχικοποιούνται ως πραγματική κάτι συνηθισμένο στον τρόπο απεικόνισης στην λογιστική.\n
    Για να   αντιμετωπίσουμε πιθανό σφάλματα Division Error που αφορά διαίρεση με το 0  αρχικοποιούμε  σε τιμή ίση με  1.0\n
    και ταυτόχρονα αποκτάμε προαιρετική χρήση μεθόδων άλλα και  επιλογή ποια ορίσματα θέλουμε.\n\n  
    ### Documentation\n
    The Gross Margin class encapsulates all those accounts that its methods use.\n 
    This accounts are initialized as real something common in the way of representation in accounting.\n 
    To deal with possible Division Error errors related to division by 0 we initialize to a value equal to 1.0\n 
    and at the same time get optional use of other methods and choice of which arguments we want.
        method :
            +gross_profit_margin
            +net_profit_margin
            +net_profits
            +return_on_equity
    """
    def __init__(self,
        gross_operating_profit: float=1.0,
        net_sales: float=1.0,
        net_operating_profit: float = 1.0,
        sales: float = 1.0,
        net_profit_of_use: float = 1.0,
        total_of_these_funds: float = 1.0) -> None:
        self.gross_operating_profit = gross_operating_profit
        self.net_sales = net_sales
        self.net_operating_profit = net_operating_profit
        self.sales = sales
        self.net_profit_of_use = net_profit_of_use
        self.total_of_these_funds = total_of_these_funds
    

    def gross_profit_margin(self) -> float:
        """
        ### Τεκμηρίωση\n
        Η μέθοδος Μικτό περιθώριο κέρδους, κληρονομεί τους λογαριασμούς από την GrossΜargin κλάση\n 
        που είναι τα μικτά κέρδη εκμετάλλευσης και καθαρές πωλήσεις.\n 
        Στην επιστροφή της μεθόδου φαίνεται ξεκάθαρα τόσο η πράξη της διαίρεσης όσο και στρογγυλοποίηση σε δυο δεκαδικά ψηφία. \n
        ### Documentation\n
        The Gross profit margin method inherits\n
        the accounts from the above class which are gross operating profit and net sales.\n
        The return of the method clearly shows both the act of division and rounding to two decimal places.
        ### round((self.gross_operating_profit /self.net_sales), 2)\n
        """
        if self.net_sales ==0:
            self.net_sales = 1.0
            return round((self.gross_operating_profit /self.net_sales), 2)
        else:
            return round((self.gross_operating_profit /self.net_sales), 2)

    def net_profit_margin(self) -> float:
        """
        ### Τεκμηρίωση\n
        Η μέθοδος περιθώριο καθαρού κέρδους,\n
        κληρονομεί τους λογαριασμούς από την GrossΜargin κλάση\n
        που είναι τα  καθαρά κέρδη εκμετάλλευσης και  καθαρές πωλήσεις.\n
        Στην επιστροφή της μεθόδου φαίνεται ξεκάθαρα  τόσο η πράξη  της διαίρεσης\n
        όσο και στρογγυλοποίηση σε δυο δεκαδικά ψηφία.\n
        ### Documentation\n
        The net profit margin method inherits\n
        the accounts from the above class which are net operating profit and net sales.\n
        The return of the method clearly shows both the division operation and rounding to two decimal places.\n 
        round((self.net_operating_profit / self.net_sales), 2)
        """
        return round((self.net_operating_profit / self.net_sales), 2)

    def net_profits(self) -> float:
        """
        Τεκμηρίωση\n
        Η μέθοδος καθαρά κέρδη,\n
        κληρονομεί τους λογαριασμούς από την GrossΜargin κλάση\n
        που είναι το   περιθώριο καθαρού κέρδους και  πωλήσεις.\n
        Στην επιστροφή της μεθόδου φαίνεται πράξη ενός μεγέθους πωλήσεις\n
        πολλαπλασιαζόμενο με την προηγούμενη μέθοδος περιθώριο καθαρού κέρδους \n
        ενώ δεν παραλείπουμε να υποχρεώσουμε το αποτελέσματα να στρογγυλοποίηση σε δυο δεκαδικά ψηφία.\n   
        Documentation\n
        The net profit method inherits the accounts from the above class which are net profit margin and sales.\n
        In the return of the method, an act of a sales size multiplied by the previous method net profit margin is shown,\n
        while we do not fail to oblige the results to be rounded to two decimal places.\n
        ### round((self.sales * self.net_profit_margin()), 2)
        """
        return round((self.sales * self.net_profit_margin()), 2)

    def return_on_equity(self) -> float:
        """
        ### Τεκμηρίωση\n
        Η μέθοδος  απόδοση ιδίων κεφαλαίων,\n
        κληρονομεί τους λογαριασμούς από την GrossΜargin κλάση\n
        που είναι τα  καθαρό κέρδος χρήσης και  συνολικά ιδων κεφαλαίων.\n
        Στην επιστροφή της μεθόδου φαίνεται ξεκάθαρα  τόσο η πράξη  της διαίρεσης\n
        όσο και στρογγυλοποίηση σε δυο δεκαδικά ψηφία.\n
        ### Documentation\n
        The return on equity method inherits\n
        the accounts from the above class which are net_profit_of_use and total_of_these_funds.\n
        The return of the method clearly shows both the division operation and rounding to two decimal places.\n 
        ### round((self.net_profit_of_use / self.total_of_these_funds), 2)
        """
        return round((self.net_profit_of_use / self.total_of_these_funds), 2)

